export const allProductsJSON = [
  {
    id: 1,
    buzo: "yes",
    remera: "no",
    campera: "no",
    destacado: "yes",
    category: "Buzos",
    img: `${process.env.PUBLIC_URL}/img/buzos/buzoProduccion.jpg`,
    name: "Buzos",
    color: "Negro",
    brand: "Buzos",
    price: "58.90",
    prevPrice: "88.90",
    sale: "sold out"
  },
  {
    id: 2,
    buzo: "yes",
    remera: "no",
    campera: "no",
    destacado: "yes",
    category: "Buzos",
    img: `${process.env.PUBLIC_URL}/img/buzos/buzoRosa.jpg`,
    name: "Buzo espalda",
    color: "Rosa",
    brand: "Buzos",
    price: "58.90",
    prevPrice: "88.90",
    sale: "sale"
  },
  {
    id: 3,
    buzo: "yes",
    remera: "no",
    campera: "no",
    destacado: "yes",
    category: "Buzos",
    img: `${process.env.PUBLIC_URL}/img/buzos/buzoBeige.jpg`,
    img2: `${process.env.PUBLIC_URL}/img/buzos/buzoBeigeMarron.jpg`,
    name: "Buzo Beige",
    color: "Beige",
    brand: "Buzos",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 4,
    buzo: "yes",
    remera: "no",
    campera: "no",
    destacado: "yes",
    category: "Buzos",
    img: `${process.env.PUBLIC_URL}/img/buzos/buzoCeleste.jpg`,
    name: "Buzo Celeste",
    color: "Celeste",
    brand: "Buzos",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 5,
    buzo: "yes",
    remera: "no",
    campera: "no",
    destacado: "yes",
    category: "Buzos",
    img: `${process.env.PUBLIC_URL}/img/buzos/buzoNegro.jpg`,
    img2: `${process.env.PUBLIC_URL}/img/buzos/buzoNegroEspalda.jpg`,
    img3: `${process.env.PUBLIC_URL}/img/buzos/buzoNegroEspaldaMole.jpg`,
    name: "Buzo Negro",
    color: "Negro",
    brand: "Buzos",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 6,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/amarillaVioleta.jpg`,
    name: "Remera Amarilla",
    color: "Amarilla Violeta",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 7,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/amarillaVioletaMole.jpg`,
    name: "Remera Amarilla",
    color: "Amarilla Violeta",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 8,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/amarilloAzulEspalda.jpg`,
    name: "Remera Amarilla Azul",
    color: "Amarilla Azul",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 9,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/amarilloAzulEspaldaMole.jpg`,
    name: "Remera Amarilla Azul",
    color: "Amarilla Azul",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 10,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/azulVioleta.jpg`,
   name: "Remera Azul Violeta",
    color: "Azul Violeta",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 11,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/azulVioletaEspalda.jpg`,
    name: "Remera Azul Violeta",
    color: "Azul Violeta",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 12,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/azulVioletaEspaldaMole.jpg`,
    name: "Remera Azul Violeta",
    color: "Azul Violeta",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 13,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/amarillaVioletaMole.jpg`,
    name: "Remera Azul Violeta",
    color: "Azul Violeta",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 14,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/blancaNaranja.jpg`,
   name: "Remera Blanca",
    color: "Blanca",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 15,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/blancaNegraEspaldaMole.jpg`,
    name: "Remera Blanca",
    color: "Blanca",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id:16,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/celesteNaranja.jpg`,
   name: "Remera Celeste Naranja",
    color: "Celeste Naranja",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 17,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/celesteVioleta.jpg`,
   name: "Remera Celeste Violeta",
    color: "Celeste Violeta",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 18,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/celesteVioletaEspalda.jpg`,
    name: "Remera Celeste Violeta",
    color: "Celeste Violeta",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 19,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/celesteVioletaMole.jpg`,
    name: "Remera Celeste Violeta",
    color: "Celeste Violeta",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  },
  {
    id: 20,
    buzo: "no",
    remera: "yes",
    campera: "no",
    destacado: "yes",
    category: "Remeras",
    img: `${process.env.PUBLIC_URL}/img/remeras/espaldaModelo.jpg`,
   name: "Remera Negra",
    color: "Negro",
    brand: "Remeras",
    price: "4379",
    prevPrice: "7599",
    sale: "sale"
  }
]